Django_course/Project1/mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("reviews/", include("reviews.urls")),
]

Django_course/Project1/reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"
urlpatterns = [
    path("", views.index, name="index"),
    path("add_book/", views.create_book, name="create_book"),
    path("contact/", views.contact_view, name="contact_view"),
    path("book/<int:id>/", views.book_detail, name="book_detail"),
    path("book/<int:book_id>/edit/", views.edit_book, name="edit_book"),
]

Django_course/Project1/reviews/models.py
from django.db import models


# Create your models here.
class Publisher(models.Model):
    name = models.CharField(max_length=50, help_text="The name of the publisher")
    website = models.URLField(help_text="The publisher's webite")
    email = models.EmailField(help_text="The publisher's email address")

    def __str__(self):
        return self.name


class Contributor(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return self.first_name


class Book(models.Model):
    PUBLICATION_STATUS = (("published", "published"), ("unpublished", "unpublished"))
    title = models.CharField(max_length=70)
    publication_date = models.DateField()
    isbn = models.CharField(max_length=20)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    contributors = models.ManyToManyField(Contributor, through="BookContributor")
    status = models.CharField(
        max_length=100, choices=PUBLICATION_STATUS, default="unpublished"
    )

    def __str__(self):
        return self.title


class BookContributor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    contributor = models.ForeignKey(Contributor, on_delete=models.CASCADE)
    role = models.CharField(
        max_length=30, help_text="Role of the contributor (e.g. Auther, Editor)"
    )


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "تماس"
        verbose_name_plural = "تماس ها"

Django_course/Project1/reviews/forms.py
from django import forms
from .models import Book


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    message = forms.CharField()

    def clean_email(self):
        email = self.cleaned_data["email"]
        if not email.endswith("@gmail.com"):
            raise forms.ValidationError("Only @gmail.com are allowed")
        return email


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ("title", "publisher", "publication_date")
        widgets = {
            "title": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter title"}
            )
        }


class SignupForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password and confirm_password:
            if password != confirm_password:
                raise forms.ValidationError("Password do not match")

        return cleaned_data

Django_course/Project1/reviews/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Book, Publisher, Contributor, Contact
from .forms import ContactForm, BookForm


def index(request):
    books = Book.objects.all()
    return render(request, "reviews/book_list.html", {"books": books})


def book_detail(request, id):
    details = Book.objects.get(id=id)
    return render(request, "reviews/book_details.html", {"details": details})


def contact_view(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            email = form.cleaned_data["email"]
            message = form.cleaned_data["message"]
            new_contact_object = Contact(name=name, email=email, message=message)
            new_contact_object.save()
            return render(request, "reviews/success.html")
    else:
        form = ContactForm()

    return render(request, "reviews/contact.html", {"form": form})


def create_book(request):
    if request.method == "POST":
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("reviews:create_book")
    else:
        form = BookForm()
    return render(request, "reviews/book_form.html", {"form": form})


def edit_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    if request.method == "POST":
        form = BookForm(request.POST, instance=book)
        if form.is_valid():
            form.save()
            return redirect("reviews:book_detail", id=book_id)
    else:
        form = BookForm(instance=book)
    return render(request, "reviews/edit_book.html", {"form": form})

Django_course/Project1/reviews/templates/reviews/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="GET">
        <input type="text" name="name" value="blalalla">
        <button>submit</button>
    </form>
    <h1>Hello World</h1>
    <p>Welcome to {{name}} class</p>
</body>
</html>

Django_course/Project1/reviews/templates/reviews/book_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ details.title }}</h1>
    <div>{{ details.publication_date }}</div>
    <div>{{ details.isbn }}</div>
    <div>{{ details.publisher }}</div>
    <div>{{ details.contributors }}</div>
    <a href="{% url 'reviews:edit_book' details.id %}">edit</a>
</body>
</html>

Django_course/Project1/reviews/templates/reviews/book_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {{form}}
        <button type="submit">add</button>
    </form>
</body>
</html>

Django_course/Project1/reviews/templates/reviews/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>All books</h1>
    {% for book in books %}
    <div>
        <a href="{% url 'reviews:book_detail' book.pk %}">{{ book.title }}</a>
        
    </div>
    {% endfor %}
</body>
</html>

Django_course/Project1/reviews/templates/reviews/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="">
        {% csrf_token %}
        {{form.name}}
        {{form.email}}
        <button>Submit</button>
    </form>
</body>
</html>

Django_course/Project1/reviews/templates/reviews/edit_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <button>Edit</button>
    </form>
</body>
</html>

Django_course/Project1/reviews/templates/reviews/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    success
</body>
</html>